### ISSUE TITLE
Crash (Loading Game)

### ISSUE THREAD

**Issue by SuperKoyek** [DaveyL2013/secrets-no-more#4]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 04.06.20 12:27
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_310.<init>(class_310.java:445)
	at net.minecraft.client.main.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method initFbo(IIZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.satin.client.json:gl.DepthGlFramebufferMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Satin-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_310.<init>(class_310.java:445)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w22a
	Minecraft Version ID: 20w22a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1351253760 bytes (1288 MB) / 1946157056 bytes (1856 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.11.2+build.351-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c0b
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.5+0e8ef4f80b
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890b
		fabric-command-api-v1: Fabric Command API (v1) 1.0.3+da175ad60b
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308360b
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b60b
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.7+da175ad60b
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0b
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.1+6d41837a0b
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd780b
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.12+63435d4b0b
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.2+4a08d6b20b
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.8+da175ad60b
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce990b
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60b
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b0b
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd780b
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.1+c6ab3e1b0b
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad60b
		fabric-particles-v1: fabric-particles-v1 0.1.3+4a08d6b20b
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.4+da175ad60b
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb80b
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.0+4a01746c0b
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600b
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0b
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c0b
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900b
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.1+1aa9d4720b
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.0+da175ad60b
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.4+2fd224ca0b
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb80b
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.1+da175ad60b
		fabricloader: Fabric Loader 0.8.6+build.200
		minecraft: Minecraft 1.16-alpha.20.22.a
		satin: Satin 1.4.0-nightly.19w46b+build.1
		snm: Secrets No More 1.1.1
	Launched Version: fabric-loader-0.8.6+build.200-20w22a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by DaveyL2013** [comment]
I'll look into it as soon as I can, right now my jdk environment is all screwed up and a lot of other things are too.

**Comment by DaveyL2013** [comment]
Fixed!
